#!/usr/bin/env python3
"""Load the committed POP909 exposure-weight table for pool arithmetic.

The table (pop909_exposure_weights.json, generated by pop909_exposure.py)
maps canonical pool case ids to their share of observed playing time in the
POP909 corpus. It is measurement support only: weighted numbers are always
reported alongside, never instead of, unweighted counts
(research/performed-input/log/2026-07-28-04).
"""

from __future__ import annotations

import json
from collections.abc import Iterable
from pathlib import Path

DEFAULT_PATH = Path(__file__).resolve().parent / "pop909_exposure_weights.json"


def load_weights(path: Path | None = None) -> dict[str, float] | None:
    """Case id to observed-mass share, or None when the table is absent."""
    table_path = path or DEFAULT_PATH
    if not table_path.exists():
        return None
    table = json.loads(table_path.read_text())
    return {case_id: entry["share"] for case_id, entry in table["weights"].items()}


def mass_share(weights: dict[str, float], case_ids: Iterable[str]) -> float:
    return sum(weights.get(case_id, 0.0) for case_id in case_ids)
